# Generated by Django 3.2.3 on 2021-05-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210521_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingcomment',
            old_name='content',
            new_name='comment',
        ),
    ]
