# Generated by Django 3.2.3 on 2021-05-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(related_name='category_listings', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(related_name='listing_categories', to='auctions.Listing'),
        ),
    ]
